<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CatSubtopicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subTopic = [
            ['id' =>1, 'cat_topic_id' =>1, 'name' => 'A1.1.-Acceso a la justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>2, 'cat_topic_id' =>1, 'name' => 'A1.2.-Debido proceso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>3, 'cat_topic_id' =>1, 'name' => 'A1.3.-Arraigo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>4, 'cat_topic_id' =>1, 'name' => 'A1.4.-Defensoría pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>5, 'cat_topic_id' =>1, 'name' => 'A1.5.-Investigación de delitos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>6, 'cat_topic_id' =>1, 'name' => 'A1.6.-Sistema de justicia penal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>7, 'cat_topic_id' =>1, 'name' => 'A1.7.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>8, 'cat_topic_id' =>1, 'name' => 'A1.8.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>9, 'cat_topic_id' =>2, 'name' => 'A2.1.-Defensoría pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>10, 'cat_topic_id' =>2, 'name' => 'A2.2.-Fortalecimiento institucional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>11, 'cat_topic_id' =>2, 'name' => 'A2.3.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>12, 'cat_topic_id' =>2, 'name' => 'A2.4.-Participación de la sociedad civil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>13, 'cat_topic_id' =>2, 'name' => 'A2.5.-Corrupción', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>14, 'cat_topic_id' =>2, 'name' => 'A2.6.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>15, 'cat_topic_id' =>3, 'name' => 'A3.1.-Acceso a la verdad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>16, 'cat_topic_id' =>3, 'name' => 'A3.2.-Atención a víctimas de desaparición forzada y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>17, 'cat_topic_id' =>3, 'name' => 'A3.3.-Comisiones de búsqueda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>18, 'cat_topic_id' =>3, 'name' => 'A3.4.-Cooperación internacional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>19, 'cat_topic_id' =>3, 'name' => 'A3.5.-Fortalecimiento institucional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>20, 'cat_topic_id' =>3, 'name' => 'A3.6.-Registro de personas desaparecidas e integración de bases de datos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>21, 'cat_topic_id' =>3, 'name' => 'A3.7.-Reparación integral a víctimas y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>22, 'cat_topic_id' =>3, 'name' => 'A3.8.-Armonizacion legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>23, 'cat_topic_id' =>3, 'name' => 'A3.9.-Recursos materiales y humanos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>24, 'cat_topic_id' =>3, 'name' => 'A3.10.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>25, 'cat_topic_id' =>4, 'name' => 'A4.1.-Asignación de presupuesto', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>26, 'cat_topic_id' =>4, 'name' => 'A4.2.-Acceso al agua potable e infraestructura de saneamiento', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>27, 'cat_topic_id' =>4, 'name' => 'A4.3.-Acceso a un nivel de vida adecuado', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>28, 'cat_topic_id' =>4, 'name' => 'A4.4.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>29, 'cat_topic_id' =>4, 'name' => 'A4.5.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>30, 'cat_topic_id' =>5, 'name' => 'A5.1.-Abusos cometidos durante detenciones', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>31, 'cat_topic_id' =>5, 'name' => 'A5.2.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>32, 'cat_topic_id' =>5, 'name' => 'A5.3.-Educación, capacitación y/o sensibilización en derechos humanos a miembros de las Fuerzas Armadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>33, 'cat_topic_id' =>5, 'name' => 'A5.4.-Defensoría Pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>34, 'cat_topic_id' =>5, 'name' => 'A5.5.-Fortalecimiento institucional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>35, 'cat_topic_id' =>5, 'name' => 'A5.6.-Mejora de las condiciones en centros de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>36, 'cat_topic_id' =>5, 'name' => 'A5.7.-Participación de las Fuerzas Armadas en tareas de seguridad pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>37, 'cat_topic_id' =>5, 'name' => 'A5.8.-Procedimientos de detención adecuados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>38, 'cat_topic_id' =>5, 'name' => 'A5.9.-Reparación integral a personas víctimas de detención arbitraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>39, 'cat_topic_id' =>5, 'name' => 'A5.10.-Sistema de justicia penal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>40, 'cat_topic_id' =>5, 'name' => 'A5.11.-Detención de personas migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>41, 'cat_topic_id' =>5, 'name' => 'A5.12.-Registro de detenciones', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>42, 'cat_topic_id' =>5, 'name' => 'A5.13.-Condiciones de las personas privadas de su libertad y de los centros de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>43, 'cat_topic_id' =>5, 'name' => 'A5.14.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>44, 'cat_topic_id' =>6, 'name' => 'A6.1.-Acceso a actividades deportivas y recreativas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>45, 'cat_topic_id' =>6, 'name' => 'A6.3.-Medidas para mejorar el acceso a la educación', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>46, 'cat_topic_id' =>6, 'name' => 'A6.2.-Acceso a la educación para niñas, niños y adolescentes indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>47, 'cat_topic_id' =>6, 'name' => 'A6.4.-Combate a la deserción escolar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>48, 'cat_topic_id' =>6, 'name' => 'A6.5.-Diversidad lingüística y cultural', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>49, 'cat_topic_id' =>6, 'name' => 'A6.6.-Educación con perspectiva de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>50, 'cat_topic_id' =>6, 'name' => 'A6.7.-Educación para grupos en situación de vulnerabilidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>51, 'cat_topic_id' =>6, 'name' => 'A6.8.-Educación para pueblos indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>52, 'cat_topic_id' =>6, 'name' => 'A6.9.-Educación, capacitación y/o sensibilización en Derechos Humanos a personas servidoras públicas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>53, 'cat_topic_id' =>6, 'name' => 'A6.10.-Medidas para disminuir el rezago educativo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>54, 'cat_topic_id' =>6, 'name' => 'A6.11.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>55, 'cat_topic_id' =>6, 'name' => 'A6.12.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>56, 'cat_topic_id' =>7, 'name' => 'A7.1.-Armonizacion legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>57, 'cat_topic_id' =>7, 'name' => 'A7.2.-Ejecuciones extrajudiciales cometidas por agentes del Estado', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>58, 'cat_topic_id' =>7, 'name' => 'A7.3.-Guerra sucia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>59, 'cat_topic_id' =>7, 'name' => 'A7.4.-Investigación de ejecuciones extrajudiciales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>60, 'cat_topic_id' =>7, 'name' => 'A7.5.-Jurisdicción militar en casos de violaciones a los derechos humanos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>61, 'cat_topic_id' =>7, 'name' => 'A7.6.-Ratificación de instrumentos internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>62, 'cat_topic_id' =>7, 'name' => 'A7.7.-Transparencia y rendición de cuentas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>63, 'cat_topic_id' =>7, 'name' => 'A7.8.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>64, 'cat_topic_id' =>7, 'name' => 'A7.9.-Garantías de no repetición', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>65, 'cat_topic_id' =>7, 'name' => 'A7.10.-Reparación integral a personas víctimas de detención arbitraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>66, 'cat_topic_id' =>8, 'name' => 'A8.1.-Consulta previa, libre e informada a pueblos y comunidades indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>67, 'cat_topic_id' =>8, 'name' => 'A8.2.-Fortalecimiento del marco regulatorio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>68, 'cat_topic_id' =>8, 'name' => 'A8.3.-Impacto ambiental de la actividad empresarial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>69, 'cat_topic_id' =>8, 'name' => 'A8.4.-Plan de Acción Nacional sobre Empresas y Derechos Humanos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>70, 'cat_topic_id' =>8, 'name' => 'A8.5.-Respeto a los derechos humanos en actividades empresariales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>71, 'cat_topic_id' =>8, 'name' => 'A8.6.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>72, 'cat_topic_id' =>8, 'name' => 'A8.7.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>73, 'cat_topic_id' =>9, 'name' => 'A9.1.-Capacitación y/o sensibilización a miembros de las Fuerzas Armadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>74, 'cat_topic_id' =>9, 'name' => 'A9.2.-Desapariciones forzadas cometidas por miembros de las Fuerzas Armadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>75, 'cat_topic_id' =>9, 'name' => 'A9.3.-Detenciones arbitrarias cometidas por miembros de las Fuerzas Armadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>76, 'cat_topic_id' =>9, 'name' => 'A9.4.-Ejecuciones extrajudiciales cometidas por miembros de las Fuerzas Armadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>77, 'cat_topic_id' =>9, 'name' => 'A9.5.-Garantías de no repetición', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>78, 'cat_topic_id' =>9, 'name' => 'A9.6.-Jurisdicción militar en casos de violaciones a los derechos humanos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>79, 'cat_topic_id' =>9, 'name' => 'A9.7.-Participación de las Fuerzas Armadas en tareas de seguridad pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>80, 'cat_topic_id' =>9, 'name' => 'A9.8.-Regulación del uso legítimo de la fuerza', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>81, 'cat_topic_id' =>9, 'name' => 'A9.9.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>82, 'cat_topic_id' =>10, 'name' => 'A10.1.-Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>83, 'cat_topic_id' =>10, 'name' => 'A10.2.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>84, 'cat_topic_id' =>10, 'name' => 'A10.3.-Amnistía', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>85, 'cat_topic_id' =>10, 'name' => 'A10.4.-Fortalecimiento de las instituciones de justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>86, 'cat_topic_id' =>11, 'name' => 'A11.1.-Libertad de expresión', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>87, 'cat_topic_id' =>11, 'name' => 'A11.2.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>88, 'cat_topic_id' =>11, 'name' => 'A11.3.-Investigación de delitos contra de personas defensoras de derechos humanos y periodistas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>89, 'cat_topic_id' =>11, 'name' => 'A11.4.-Protección de personas defensoras de derechos humanos y periodistas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>90, 'cat_topic_id' =>11, 'name' => 'A11.5.-Protesta social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>91, 'cat_topic_id' =>11, 'name' => 'A11.6.-Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>92, 'cat_topic_id' =>11, 'name' => 'A11.7.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>93, 'cat_topic_id' =>11, 'name' => 'A11.8.-Diversidad y pluralismo en los medios de comunicación', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>94, 'cat_topic_id' =>12, 'name' => 'A12.1.-Consulta previa, libre e informada a pueblos y comunidades indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>95, 'cat_topic_id' =>12, 'name' => 'A12.2.-Desechos peligrosos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>96, 'cat_topic_id' =>12, 'name' => 'A12.3.-Medio ambiente y cambio climático', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>97, 'cat_topic_id' =>12, 'name' => 'A12.4.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>98, 'cat_topic_id' =>12, 'name' => 'A12.5.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>99, 'cat_topic_id' =>13, 'name' => 'A13.1.-Acceso a la justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>100, 'cat_topic_id' =>13, 'name' => 'A13.2.-Ciudad Juárez', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>101, 'cat_topic_id' =>13, 'name' => 'A13.3.-Feminicidio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>102, 'cat_topic_id' =>13, 'name' => 'A13.4.-Igualdad entre mujeres y hombres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>103, 'cat_topic_id' =>13, 'name' => 'A13.5.-Implementación y promoción de programas en favor de las mujeres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>104, 'cat_topic_id' =>13, 'name' => 'A13.6.-Interrupción legal del embarazo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>105, 'cat_topic_id' =>13, 'name' => 'A13.7.-Investigación de delitos cometidos contra mujeres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>106, 'cat_topic_id' =>13, 'name' => 'A13.8.-Mujeres afromexicanas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>107, 'cat_topic_id' =>13, 'name' => 'A13.9.-Mujeres en centros de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>108, 'cat_topic_id' =>13, 'name' => 'A13.10.-Mujeres indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>109, 'cat_topic_id' =>13, 'name' => 'A13.11.-Mujeres trabajadoras', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>110, 'cat_topic_id' =>13, 'name' => 'A13.12.-Mujeres trabajadoras migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>111, 'cat_topic_id' =>13, 'name' => 'A13.13.-Perspectiva de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>112, 'cat_topic_id' =>13, 'name' => 'A13.14.-Paridad de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>113, 'cat_topic_id' =>13, 'name' => 'A13.15.-Ratificación de instrumentos internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>114, 'cat_topic_id' =>13, 'name' => 'A13.16.-Salud sexual y reproductiva', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>115, 'cat_topic_id' =>13, 'name' => 'A13.17.-Trabajo doméstico', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>116, 'cat_topic_id' =>13, 'name' => 'A13.18.-Tráfico ilícito de mujeres y niñas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>117, 'cat_topic_id' =>13, 'name' => 'A13.19.-Trata de mujeres y niñas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>118, 'cat_topic_id' =>13, 'name' => 'A13.20.-Violencia contra las mujeres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>119, 'cat_topic_id' =>13, 'name' => 'A13.21.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>120, 'cat_topic_id' =>13, 'name' => 'A13.22-Reparacion integral a mujeres víctimas de violaciones a derechos humanos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>121, 'cat_topic_id' =>13, 'name' => 'A13.23.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>122, 'cat_topic_id' =>13, 'name' => 'A13.24.-Mujeres con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>123, 'cat_topic_id' =>14, 'name' => 'A14.1.-Acceso a la educación para niñas, niños y adolescentes indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>124, 'cat_topic_id' =>14, 'name' => 'A14.2.-Disfrute del máximo nivel de salud de niños, niñas y adolescentes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>125, 'cat_topic_id' =>14, 'name' => 'A14.3.-Interés superior de la niñez', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>126, 'cat_topic_id' =>14, 'name' => 'A14.4.-Matrimonio infantil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>127, 'cat_topic_id' =>14, 'name' => 'A14.5.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>128, 'cat_topic_id' =>14, 'name' => 'A14.6.-Niñas, niños y adolescentes migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>129, 'cat_topic_id' =>14, 'name' => 'A14.7.-Niñas, niños y adolescentes migrantes no acompañados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>130, 'cat_topic_id' =>14, 'name' => 'A14.8.-Niñas, niños y adolescentes solicitantes de la condición de refugiado', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>131, 'cat_topic_id' =>14, 'name' => 'A14.9.-Niñas, niños y adolescentes indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>132, 'cat_topic_id' =>14, 'name' => 'A14.10.-Reparacion integral a personas víctimas de violaciones a derechos humanos y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>133, 'cat_topic_id' =>14, 'name' => 'A14.11.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>134, 'cat_topic_id' =>14, 'name' => 'A14.12.-Niñas, niños y adolescentes con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>135, 'cat_topic_id' =>15, 'name' => 'A15.1.-Discriminación contra las mujeres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>136, 'cat_topic_id' =>15, 'name' => 'A15.2.-Discriminación contra personas LGBTTTIQ+', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>137, 'cat_topic_id' =>15, 'name' => 'A15.3.-Discriminación contra personas y comunidades indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>138, 'cat_topic_id' =>15, 'name' => 'A15.4.-Discriminación racial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>139, 'cat_topic_id' =>15, 'name' => 'A15.5.-Acciones afirmativas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>140, 'cat_topic_id' =>15, 'name' => 'A15.6.-Discriminación contra personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>141, 'cat_topic_id' =>15, 'name' => 'A15.7.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>142, 'cat_topic_id' =>16, 'name' => 'A32.1.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>143, 'cat_topic_id' =>17, 'name' => 'A16.1.-Acceso a la justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>144, 'cat_topic_id' =>17, 'name' => 'A16.2.-Discriminación racial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>145, 'cat_topic_id' =>17, 'name' => 'A16.3.-Reconocimiento a las personas afromexicanas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>146, 'cat_topic_id' =>17, 'name' => 'A16.4.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>147, 'cat_topic_id' =>18, 'name' => 'A17.1.-Ajustes razonables', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>148, 'cat_topic_id' =>18, 'name' => 'A17.2.-Capacidad jurídica de personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>149, 'cat_topic_id' =>18, 'name' => 'A17.3.-Capacitación y/o sensibilización a miembros de las Fuerzas Armadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>150, 'cat_topic_id' =>18, 'name' => 'A17.4.-Consentimiento libre e informado', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>151, 'cat_topic_id' =>18, 'name' => 'A17.5.-Institucionalización de personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>152, 'cat_topic_id' =>18, 'name' => 'A17.6.-Medidas de accesibilidad e inclusión', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>153, 'cat_topic_id' =>18, 'name' => 'A17.7.-Personas con discapacidad en zonas rurales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>154, 'cat_topic_id' =>18, 'name' => 'A17.8.-Protección de personas con discapacidad víctimas de violencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>155, 'cat_topic_id' =>18, 'name' => 'A17.9.-Toma de decisiones', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>156, 'cat_topic_id' =>18, 'name' => 'A17.10.-Acciones afirmativas para personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>157, 'cat_topic_id' =>18, 'name' => 'A17.11.-Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>158, 'cat_topic_id' =>18, 'name' => 'A17.12.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>159, 'cat_topic_id' =>18, 'name' => 'A17.13.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>160, 'cat_topic_id' =>19, 'name' => 'A18.1.-Acceso a la información', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>161, 'cat_topic_id' =>19, 'name' => 'A18.2.-Diversidad y pluralismo en los medios de comunicación', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>162, 'cat_topic_id' =>19, 'name' => 'A18.3.-Investigación de delitos contra de personas defensoras de derechos humanos y periodistas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>163, 'cat_topic_id' =>19, 'name' => 'A18.4.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>164, 'cat_topic_id' =>19, 'name' => 'A18.5.-Participación de la sociedad civil y las víctimas en la búsqueda de personas desaparecidas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>165, 'cat_topic_id' =>19, 'name' => 'A18.6.-Prevención de delitos cometidos contra personas defensoras de derechos humanos y periodistas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>166, 'cat_topic_id' =>19, 'name' => 'A18.7.-Protección de personas defensoras de derechos humanos y periodistas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>167, 'cat_topic_id' =>19, 'name' => 'A18.8.-Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>168, 'cat_topic_id' =>19, 'name' => 'A18.9.- Acceso a la justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>169, 'cat_topic_id' =>19, 'name' => 'A18.10.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>170, 'cat_topic_id' =>20, 'name' => 'A19.1.-Medidas de atención a personas desplazadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>171, 'cat_topic_id' =>20, 'name' => 'A19.2.-Planes de retorno para personas desplazadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>172, 'cat_topic_id' =>20, 'name' => 'A19.3.-Protección a personas desplazadas internas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>173, 'cat_topic_id' =>20, 'name' => 'A19.4.-Reasentamiento de personas desplazadas internas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>174, 'cat_topic_id' =>20, 'name' => 'A19.5.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>175, 'cat_topic_id' =>20, 'name' => 'A19.6.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>176, 'cat_topic_id' =>21, 'name' => 'A20.1.-Discriminación contra personas LGBTTTIQ+', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>177, 'cat_topic_id' =>21, 'name' => 'A20.2.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>178, 'cat_topic_id' =>22, 'name' => 'A21.1.-Acceso a la educación para personas migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>179, 'cat_topic_id' =>22, 'name' => 'A21.2.-Acceso a la justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>180, 'cat_topic_id' =>22, 'name' => 'A21.3.-Acceso a la salud para personas migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>181, 'cat_topic_id' =>22, 'name' => 'A21.4.-Alternativas a la detención migratoria / alojamiento en estaciones migratorias', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>182, 'cat_topic_id' =>22, 'name' => 'A21.5.-Búsqueda de personas migrantes bajo cualquier forma de privación de la libertad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>183, 'cat_topic_id' =>22, 'name' => 'A21.6.-Educación,capacitación y/o sensibilización en derechos humanos a personas servidoras públicas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>184, 'cat_topic_id' =>22, 'name' => 'A21.7.-Estaciones migratorias', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>185, 'cat_topic_id' =>22, 'name' => 'A21.8.-Acceso a la justicia para personas migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>186, 'cat_topic_id' =>22, 'name' => 'A21.9.-Participación de la sociedad civil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>187, 'cat_topic_id' =>22, 'name' => 'A21.10.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>188, 'cat_topic_id' =>22, 'name' => 'A21.11.-Personas migrantes, refugiadas y solicitantes de asilo con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>189, 'cat_topic_id' =>23, 'name' => 'A22.1.-Fortalecimiento institucional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>190, 'cat_topic_id' =>23, 'name' => 'A22.2.-Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>191, 'cat_topic_id' =>23, 'name' => 'A22.3.-Víctimas de tráfico ilícito de personas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>192, 'cat_topic_id' =>23, 'name' => 'A22.4.-Víctimas de trata de personas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>193, 'cat_topic_id' =>23, 'name' => 'A22.5.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>194, 'cat_topic_id' =>23, 'name' => 'A22.6.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>195, 'cat_topic_id' =>24, 'name' => 'A23.1.-Conflictos agrarios', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>196, 'cat_topic_id' =>24, 'name' => 'A23.2.-Consulta previa, libre e informada a pueblos y comunidades indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>197, 'cat_topic_id' =>24, 'name' => 'A23.3.-Diversidad lingüística y cultural', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>198, 'cat_topic_id' =>24, 'name' => 'A23.4.-Educación para pueblos indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>199, 'cat_topic_id' =>24, 'name' => 'A23.5.-Identidad y autoadscripción indígena', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>200, 'cat_topic_id' =>24, 'name' => 'A23.6.-Personas indígenas en situación de pobreza', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>201, 'cat_topic_id' =>24, 'name' => 'A23.7.-Reparación integral a personas indígenas víctimas de violaciones a derechos humanos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>202, 'cat_topic_id' =>24, 'name' => 'A23.8.-Tierra, territorio y recursos naturales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>203, 'cat_topic_id' =>24, 'name' => 'A23.9.-Sistemas normativos indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>204, 'cat_topic_id' =>24, 'name' => 'A23.10.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>205, 'cat_topic_id' =>24, 'name' => 'A23.11.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>206, 'cat_topic_id' =>24, 'name' => 'A23.12.-Personas indígenas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>207, 'cat_topic_id' =>25, 'name' => 'A24.1.-Acceso a la alimentación', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>208, 'cat_topic_id' =>25, 'name' => 'A24.2.-Acceso a la seguridad social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>209, 'cat_topic_id' =>25, 'name' => 'A24.3.-Acceso a servicios de salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>210, 'cat_topic_id' =>25, 'name' => 'A24.4.-Acceso al agua potable e infraestructura de saneamiento', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>211, 'cat_topic_id' =>25, 'name' => 'A24.5.-Consulta previa, libre e informada a pueblos y comunidades indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>212, 'cat_topic_id' =>25, 'name' => 'A24.6.-Desigualdad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>213, 'cat_topic_id' =>25, 'name' => 'A24.7.-Política agraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>214, 'cat_topic_id' =>25, 'name' => 'A24.8.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>215, 'cat_topic_id' =>25, 'name' => 'A24.9.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>216, 'cat_topic_id' =>26, 'name' => 'A25.1.-Asignación del presupuesto', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>217, 'cat_topic_id' =>26, 'name' => 'A25.2.-Consumo de drogas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>218, 'cat_topic_id' =>26, 'name' => 'A25.3.-Disfrute del máximo nivel de salud de personas en situación de vulnerabilidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>219, 'cat_topic_id' =>26, 'name' => 'A25.4.-Interrupción legal del embarazo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>220, 'cat_topic_id' =>26, 'name' => 'A25.5.-Personas viviendo con VIH/SIDA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>221, 'cat_topic_id' =>26, 'name' => 'A25.6.-Salud mental', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>222, 'cat_topic_id' =>26, 'name' => 'A25.7.-Salud sexual y reproductiva', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>223, 'cat_topic_id' =>26, 'name' => 'A25.8.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>224, 'cat_topic_id' =>27, 'name' => 'A32.1.-Difusión de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>225, 'cat_topic_id' =>27, 'name' => 'A32.2.-Elaboración de informes ante mecanismos y órganos de tratados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>226, 'cat_topic_id' =>27, 'name' => 'A32.3.-Mecanismos de coordinación interinstitucional para el seguimiento', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>227, 'cat_topic_id' =>28, 'name' => 'A26.1.-Policías y seguridad pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>228, 'cat_topic_id' =>28, 'name' => 'A26.2.-Delincuencia organizada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>229, 'cat_topic_id' =>28, 'name' => 'A26.3.-Fortalecimiento de las instituciones de seguridad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>230, 'cat_topic_id' =>28, 'name' => 'A26.4.-Lucha contra la impunidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>231, 'cat_topic_id' =>28, 'name' => 'A26.5.-Participación de las Fuerzas Armadas en tareas de seguridad pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>232, 'cat_topic_id' =>28, 'name' => 'A26.6.-Investigación de delitos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>233, 'cat_topic_id' =>28, 'name' => 'A26.7.-Regulación del uso legítimo de la fuerza', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>234, 'cat_topic_id' =>28, 'name' => 'A26.8.-Sistema de justicia penal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>235, 'cat_topic_id' =>28, 'name' => 'A26.9.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>236, 'cat_topic_id' =>28, 'name' => 'A26.10-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>237, 'cat_topic_id' =>29, 'name' => 'A27.1.-Aplicación de las Reglas Nelson Mandela para el Tratamiento de los Reclusos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>238, 'cat_topic_id' =>29, 'name' => 'A27.2.-Educación,capacitación y/o sensibilización en derechos humanos a personas servidoras públicas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>239, 'cat_topic_id' =>29, 'name' => 'A27.3.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>240, 'cat_topic_id' =>29, 'name' => 'A27.4.-Seguimiento de recomendaciones internacionales en materia de tortura', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>241, 'cat_topic_id' =>29, 'name' => 'A27.5.-Aplicación del Protocolo de Estambul', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>242, 'cat_topic_id' =>29, 'name' => 'A27.6.-Condiciones de las personas privadas de su libertad y de centros de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>243, 'cat_topic_id' =>29, 'name' => 'A27.7.-Evaluación médica forense', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>244, 'cat_topic_id' =>29, 'name' => 'A27.8.-Garantías de no repetición', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>245, 'cat_topic_id' =>29, 'name' => 'A27.9.-Mecanismo Nacional de Prevención de la Tortura', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>246, 'cat_topic_id' =>29, 'name' => 'A27.10.-Participación de la sociedad civil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>247, 'cat_topic_id' =>30, 'name' => 'A28.1.-Trabajadores migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>248, 'cat_topic_id' =>30, 'name' => 'A28.2.-Acceso a prestaciones completas de trabajo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>249, 'cat_topic_id' =>30, 'name' => 'A28.3.-Políticas de igualdad laboral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>250, 'cat_topic_id' =>30, 'name' => 'A28.4.-Jornada laboral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>251, 'cat_topic_id' =>30, 'name' => 'A28.5.-Legislación laboral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>252, 'cat_topic_id' =>30, 'name' => 'A28.6.-Libertad sindical', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>253, 'cat_topic_id' =>30, 'name' => 'A28.7.-Ratificación de instrumentos internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>254, 'cat_topic_id' =>30, 'name' => 'A28.8.-Salario mínimo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>255, 'cat_topic_id' =>30, 'name' => 'A28.9.-Seguridad social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>256, 'cat_topic_id' =>30, 'name' => 'A28.10.Personas trabajadoras agrícolas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>257, 'cat_topic_id' =>30, 'name' => 'A28.11.-Trabajo doméstico', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>258, 'cat_topic_id' =>30, 'name' => 'A28.12.-Trabajo infantil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>259, 'cat_topic_id' =>30, 'name' => 'A28.13.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>260, 'cat_topic_id' =>31, 'name' => 'A29.1.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>261, 'cat_topic_id' =>31, 'name' => 'A29.2.-Tráfico ilícito de personas migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>262, 'cat_topic_id' =>31, 'name' => 'A29.3.-Tráfico ilícito de mujeres y niñas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>263, 'cat_topic_id' =>31, 'name' => 'A29.4.-Tráfico ilícito de niñas, niños y adolescentes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>264, 'cat_topic_id' =>31, 'name' => 'A29.5.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>265, 'cat_topic_id' =>32, 'name' => 'A30.1.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>266, 'cat_topic_id' =>32, 'name' => 'A30.2.-Trata de personas migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>267, 'cat_topic_id' =>32, 'name' => 'A30.3.-Trata de mujeres y niñas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>268, 'cat_topic_id' =>32, 'name' => 'A30.4.-Trata de niñas, niños y adolescentes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>269, 'cat_topic_id' =>32, 'name' => 'A30.5.-Seguimiento de recomendaciones internacionales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>270, 'cat_topic_id' =>33, 'name' => 'A31.1.-Vivienda adecuada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>271, 'cat_topic_id' =>33, 'name' => 'A31.2.-Desalojos forzosos de vivienda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>272, 'cat_topic_id' =>33, 'name' => 'A31.3.-Políticas de fomento a la vivienda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>273, 'cat_topic_id' =>33, 'name' => 'A31.4.-Fortalecimiento del marco regulatorio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>274, 'cat_topic_id' =>33, 'name' => 'A31.5.-Vivienda social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>275, 'cat_topic_id' =>33, 'name' => 'A31.6.-Armonización legislativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

        ];
        DB::table('cat_subtopics')->insert($subTopic);
    }
}
