<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CatSubtopicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_subtopics')->insert([
            [
                'id' => 1,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'name' => 'Arraigo',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'name' => 'Debido proceso',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'name' => 'Combate a la impunidad',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'name' => 'Procedimientos de investigación de delitos',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'name' => 'Sistema de justicia penal',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'name' => 'Defensoría Pública',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'name' => 'Derecho al voto (Participación política-electoral)',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'name' => 'Paridad de género',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'name' => 'Participación de la sociedad civil',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'name' => 'Acceso a la verdad',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'name' => 'Atención a víctimas de desaparición forzada y sus familiares',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'name' => 'Comisiones de búsqueda',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'name' => 'Cooperación internacional',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'name' => 'Fortalecimiento institucional',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'name' => 'Garantías de no repetición',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'name' => 'Investigación forense',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'name' => 'Participación de la sociedad civil y las víctimas en la búsqueda de personas desaparecidas',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'name' => 'Recursos materiales y humanos',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'name' => 'Registro de personas desaparecidas e integración de bases de datos',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'name' => 'Reparación integral a víctimas y sus familiares',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'name' => 'Asignación de presupuesto',
                'cat_topic_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'name' => 'Acceso al agua potable e infraestructura de saneamiento',
                'cat_topic_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'name' => 'Acceso a un nivel de vida adecuado',
                'cat_topic_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'name' => 'Abusos cometidos durante detenciones',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'name' => 'Armonización legislativa',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'name' => 'Educación, capacitación y/o sensibilización en Derechos Humanos a miembros de las Fuerzas Armadas',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'name' => 'Defensoría Pública',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'name' => 'Fortalecimiento institucional',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'name' => 'Mejora de las condiciones en centros de detención',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'name' => 'Participación de las Fuerzas Armadas en tareas de seguridad pública',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'name' => 'Procedimientos de detención adecuados',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'name' => 'Reparación integral a personas víctimas de detención arbitraria',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'name' => 'Sistema de justicia penal',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'name' => 'Acceso a actividades deportivas y recreativas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'name' => 'Acceso a la educación para niñas, niños y adolescentes indígenas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'name' => 'Combate a la deserción escolar',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'name' => 'Diversidad lingüística y cultural',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'name' => 'Educación con perspectiva de género',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 40,
                'name' => 'Educación para grupos en situación de vulnerabilidad',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'name' => 'Educación para pueblos indígenas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 42,
                'name' => 'Educación, capacitación y/o sensibilización en Derechos Humanos a personas servidoras públicas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 43,
                'name' => 'Falta un tema de Ciencie y Tecnología',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 44,
                'name' => 'Medidas para disminuir el rezago educativo',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 45,
                'name' => 'Ejecuciones extrajudiciales cometidas por agentes del Estado',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 46,
                'name' => 'Guerra sucia',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 47,
                'name' => 'Investigación de ejecuciones extrajudiciales',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 48,
                'name' => 'Jurisdicción civil',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 49,
                'name' => 'Ratificación de instrumentos internacionales',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 50,
                'name' => 'Transparencia y rendición de cuentas',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 51,
                'name' => 'Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 52,
                'name' => 'Fortalecimiento del Marco Regulatorio',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 53,
                'name' => 'Impacto ambiental',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 54,
                'name' => 'Plan de Acción Nacional sobre Empresas y Derechos Humanos',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 55,
                'name' => 'Respeto a los derechos humanos en actividades empresariales',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 56,
                'name' => 'Capacitación y/o sensibilización a miembros de las fuerzas armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 57,
                'name' => 'Desapariciones forzadas cometidas por miembros de las Fuerzas Armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 58,
                'name' => 'Detenciones arbitrarias cometidas por miembros de las Fuerzas Armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 59,
                'name' => 'Ejecuciones extrajudiciales cometidas por miembros de las Fuerzas Armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 60,
                'name' => 'Garantías de no repetición',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 61,
                'name' => 'Jurisdicción militar en casos de violaciones a los derechos humanos',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 62,
                'name' => 'Participación de las Fuerzas Armadas en tareas de seguridad pública',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 63,
                'name' => 'Regulación del uso legítimo de la fuerza',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 64,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 65,
                'name' => 'Acceso a la verdad',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 66,
                'name' => 'Amnistía',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 67,
                'name' => 'Fortalecimiento institucional',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 68,
                'name' => 'Reparaciónintegral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 69,
                'name' => 'Acceso a la información',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 70,
                'name' => 'Armonización legislativa',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 71,
                'name' => 'Diversidad y pluralismo en los medios de comunicación',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 72,
                'name' => 'Investigación de delitos cometidos en contra de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 73,
                'name' => 'Participación de la sociedad civil',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 74,
                'name' => 'Prevención de delitos cometidos contra personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 75,
                'name' => 'Protección de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 76,
                'name' => 'Protesta social',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 77,
                'name' => 'Reparaciónintegral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 78,
                'name' => 'Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 79,
                'name' => 'Desechos peligrosos',
                'cat_topic_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 80,
                'name' => 'Medio ambiente y cambio climático',
                'cat_topic_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 81,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 82,
                'name' => 'Asesinatos cometidos contra mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 83,
                'name' => 'Ciudad Juárez',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 84,
                'name' => 'Feminicidio',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 85,
                'name' => 'Identificación de autores de delitos cometidos contra mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 86,
                'name' => 'Igualdad entre mujeres y hombres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 87,
                'name' => 'Implementación y promoción de programas en favor de las mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 88,
                'name' => 'Interrupción legal del embarazo',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 89,
                'name' => 'Investigación de delitos cometidos contra las mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 90,
                'name' => 'Mujeres afromexicanas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 91,
                'name' => 'Mujeres en centros de detención',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 92,
                'name' => 'Mujeres indígenas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 93,
                'name' => 'Mujeres trabajadoras',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 94,
                'name' => 'Mujeres trabajadoras migrantes',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 95,
                'name' => 'Perspectiva de género',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 96,
                'name' => 'Paridad de género',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 97,
                'name' => 'Ratificación de instrumentos internacionales',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 98,
                'name' => 'Salud sexual y reproductiva',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 99,
                'name' => 'Trabajo doméstico',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 100,
                'name' => 'Tráfico ilícito de mujeres y niñas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 101,
                'name' => 'Trata de mujeres y niñas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 102,
                'name' => 'Violencia contra las mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 103,
                'name' => 'Acceso a la educación para niñas, niños y adolescentes indígenas',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 104,
                'name' => 'Disfrute del máximo nivel de salud',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 105,
                'name' => 'Interés superior de la niñez',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 106,
                'name' => 'Matrimonio infantil',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 107,
                'name' => 'Armonización legislativa',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 108,
                'name' => 'Niñas, niños y adolescentes migrantes',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 109,
                'name' => 'Niñas, niños y adolescentes migrantes no acompañados',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 110,
                'name' => 'Niñas, niños y adolescentes solicitantes de la condición de refugiado',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 111,
                'name' => 'Niñas, niños y adolescentes indígenas',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 112,
                'name' => 'Discriminación contra las mujeres',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 113,
                'name' => 'Discriminación contra Personas LGBTTTIQ+',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 114,
                'name' => 'Discriminación contra personas y comunidades indígenas',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 115,
                'name' => 'Discriminación racial',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 116,
                'name' => 'Acciones Afirmativas',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 117,
                'name' => 'Discriminación contra Personas con discapacidad',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 118,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 119,
                'name' => 'Discriminación racial',
                'cat_topic_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 120,
                'name' => 'Reconocimiento a las personas afromexicanas',
                'cat_topic_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 121,
                'name' => 'Ajustes razonables',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 122,
                'name' => 'Capacidad jurídica de personas con discapacidad',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 123,
                'name' => 'Capacitación y/o sensibilización a miembros de las fuerzas armadas',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 124,
                'name' => 'Consentimiento libre e informado',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 125,
                'name' => 'Institucionalización de personas con discapacidad',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 126,
                'name' => 'Medidas de accesibilidad e inclusión',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 127,
                'name' => 'Personas con discapacidad en zonas rurales',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 128,
                'name' => 'Protección de personas con dicapacidad víctimas de violencia',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 129,
                'name' => 'Toma de decisiones',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 130,
                'name' => 'Acciones afirmativas para personas con discapacidad',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 131,
                'name' => 'Acceso a la información',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 132,
                'name' => 'Diversidad y pluralismo en los medios de comunicación',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 133,
                'name' => 'Investigación de delitos cometidos en contra de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 134,
                'name' => 'Armonización legislativa',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 135,
                'name' => 'Participación de la sociedad civil y las víctimas en la búsqueda de personas desaparecidas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 136,
                'name' => 'Prevención de delitos cometidos contra personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 137,
                'name' => 'Protección de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 138,
                'name' => 'Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 139,
                'name' => 'Medidas de atención a personas desplazadas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 140,
                'name' => 'Planes de retorno para personas desplazadas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 141,
                'name' => 'Protección a personas desplazadas internas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 142,
                'name' => 'Reasentamiento de personas desplazadas internas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 143,
                'name' => 'Discriminación contra Personas LGBTTTIQ+',
                'cat_topic_id' => 20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 144,
                'name' => 'Acceso a la educación para personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 145,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 146,
                'name' => 'Acceso a la salud para personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 147,
                'name' => 'Alternativas a la detención migratoria / alojamiento en estaciones migratorias',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 148,
                'name' => 'Búsqueda de personas migrantes desaparecidas, no localizadas, secuestradas o bajo cualquier forma de privación de la ',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 149,
                'name' => 'Educación, capacitación y/o sensibilización en derechos humanos a personas servidoras públicas',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 150,
                'name' => 'Estaciones migratorias',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 151,
                'name' => 'Gestión migratoria',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 152,
                'name' => 'Mujeres trabajadoras migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 153,
                'name' => 'Mujeres trabajadoras migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 154,
                'name' => 'Niñas, niños y adolescentes migrantes no acompañados',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 155,
                'name' => 'Niñas, niños y adolescentes solicitantes del reconocimiento de la condición de refugiado',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 156,
                'name' => 'Participación de la sociedad civil',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 157,
                'name' => 'Personas trabajadoras migrantes mexicanas',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 158,
                'name' => 'Personas trabajadoras migrantes y sus familiares',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 159,
                'name' => 'Protección a personas migrantes, solicitantes de la condición de refugio y refugiadas',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 160,
                'name' => 'Tráfico ilícito de personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 161,
                'name' => 'Trata de personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 162,
                'name' => 'Unidad de investigación de delitos cometidos contra personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 163,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 164,
                'name' => 'Acceso a la verdad',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 165,
                'name' => 'Comisiones de atención a víctimas',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 166,
                'name' => 'Fortalecimiento institucional',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 167,
                'name' => 'Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 168,
                'name' => 'Víctimas de tráfico ilícito de personas',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 169,
                'name' => 'Víctimas de trata de personas',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 170,
                'name' => 'Conflictos agrarios',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 171,
                'name' => 'Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 172,
                'name' => 'Diversidad lingüística y cultural',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 173,
                'name' => 'Educación para pueblos indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 174,
                'name' => 'Identidad y autoadscripción indígena',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 175,
                'name' => 'Personas indígenas en situación de pobreza extrema',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 176,
                'name' => 'Respeto a usos y costumbres de personas y comunidades indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 177,
                'name' => 'Tierra, territorio y recursos naturales',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 178,
                'name' => 'Sistemas normativos indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 179,
                'name' => 'Traductores e intérpretes para personas indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 180,
                'name' => 'Acceso a la alimentación',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 181,
                'name' => 'Acceso a la seguridad social',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 182,
                'name' => 'Acceso a servicios de salud',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 183,
                'name' => 'Acceso al agua potable e infraestructura de saneamiento',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 184,
                'name' => 'Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 185,
                'name' => 'Desigualdad',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 186,
                'name' => 'Política agraria',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 187,
                'name' => 'Seguridad social',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 188,
                'name' => 'Acceso a la seguridad social',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 189,
                'name' => 'Asignación de presupuesto',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 190,
                'name' => 'Consumo de drogas',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 191,
                'name' => 'Interrupción legal del embarazo',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 192,
                'name' => 'Personas viviendo con VIH/SIDA',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 193,
                'name' => 'Salud mental',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 194,
                'name' => 'Salud sexual y reproductiva',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 195,
                'name' => 'Acceso a la justicia',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 196,
                'name' => 'Amnistía',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 197,
                'name' => 'Debido proceso judicial',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 198,
                'name' => 'arb',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 199,
                'name' => 'fut',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 200,
                'name' => 'francia',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 201,
                'name' => 'fer',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 202,
                'name' => 'fuente',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 203,
                'name' => 'cerro',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 204,
                'name' => 'saul',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 205,
                'name' => 'lopez',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 206,
                'name' => 'amnistia',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 207,
                'name' => 'paz',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 208,
                'name' => 'fe',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 209,
                'name' => 'japones',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 210,
                'name' => 'chino',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 211,
                'name' => 'frances',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 212,
                'name' => 'ingles',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 213,
                'name' => 'bromo',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 214,
                'name' => 'pimi',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 215,
                'name' => 'sal',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 216,
                'name' => 'derecha',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 217,
                'name' => 'rojo',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 218,
                'name' => 'borre',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 219,
                'name' => 'jose',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 220,
                'name' => 'javier',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 221,
                'name' => 'hoy',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 222,
                'name' => 'amarillo',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 223,
                'name' => 'verde',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 224,
                'name' => 'ya',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 225,
                'name' => 'rojo',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 226,
                'name' => 'azul',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 227,
                'name' => 'red',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 228,
                'name' => 'jirafa',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 229,
                'name' => 'raul',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 230,
                'name' => 'hora',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 231,
                'name' => 'gramo',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 232,
                'name' => 'kilo',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 233,
                'name' => 'abajo',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 234,
                'name' => 'arriba',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 235,
                'name' => 'gato',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 236,
                'name' => 'perro',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 237,
                'name' => 'manuel',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 238,
                'name' => 'juan',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 239,
                'name' => 'ivan',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 240,
                'name' => 'roberto',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 241,
                'name' => 'maria',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 242,
                'name' => 'luna',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 243,
                'name' => 'lina',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 244,
                'name' => 'sol',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 245,
                'name' => 'lluvia',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 246,
                'name' => 'fierro',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 247,
                'name' => 'koala',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 248,
                'name' => 'hola',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
