<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class CatSubtopicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_subtopics')->insert([
            [
                'id' => 1,
                'name' => 'A1.1.- Acceso a la justicia',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'name' => 'A1.2.- Arraigo',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'name' => 'A1.3.- Debido proceso',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'name' => 'A1.4.- Combate a la impunidad',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'name' => 'A1.5.- Procedimientos de investigación de delitos',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'name' => 'A1.6.- Sistema de justicia penal',
                'cat_topic_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'name' => 'A2.1.- Defensoría Pública',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'name' => 'A2.2.- Derecho al voto (Participación política-electoral)',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'name' => 'A2.3.- Paridad de género',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'name' => 'A2.4.- Participación de la sociedad civil',
                'cat_topic_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'name' => 'A3.1.- Acceso a la verdad',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'name' => 'A3.2.- Atención a víctimas de desaparición forzada y sus familiares',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'name' => 'A3.3.- Comisiones de búsqueda',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'name' => 'A3.4.- Cooperación internacional',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'name' => 'A3.5.- Fortalecimiento institucional',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'name' => 'A3.6.- Garantías de no repetición',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'name' => 'A3.7.- Investigación forense',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'name' => 'A3.8.- Participación de la sociedad civil y las víctimas en la búsqueda de personas desaparecidas',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'name' => ' A3.9.- Recursos materiales y humanos',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'name' => 'A3.10.- Registro de personas desaparecidas e integración de bases de datos',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'name' => 'A3.11.- Reparación integral a víctimas y sus familiares',
                'cat_topic_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'name' => 'A4.1.- Asignación de presupuesto',
                'cat_topic_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'name' => 'A4.2.- Acceso al agua potable e infraestructura de saneamiento',
                'cat_topic_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'name' => 'A4.3.- Acceso a un nivel de vida adecuado',
                'cat_topic_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'name' => 'A5.1.- Abusos cometidos durante detenciones',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'name' => 'A5.2.- Armonización legislativa',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'name' => 'A5.3.- Educación, capacitación y/o sensibilización en Derechos Humanos a miembros de las Fuerzas Armadas',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'name' => 'A5.4.- Defensoría Pública',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'name' => 'A5.5.- Fortalecimiento institucional',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'name' => 'A5.6.- Mejora de las condiciones en centros de detención',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'name' => 'A5.7.- Participación de las Fuerzas Armadas en tareas de seguridad pública',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'name' => 'A5.8.- Procedimientos de detención adecuados',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'name' => 'A5.9.- Reparación integral a personas víctimas de detención arbitraria',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'name' => 'A5.10.- Sistema de justicia penal',
                'cat_topic_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'name' => 'A6.1.- Acceso a actividades deportivas y recreativas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'name' => 'A6.2.- Acceso a la educación para niñas, niños y adolescentes indígenas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'name' => 'A6.3.- Combate a la deserción escolar',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'name' => 'A6.4.- Diversidad lingüística y cultural',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'name' => 'A6.5.- Educación con perspectiva de género',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 40,
                'name' => 'A6.6.- Educación para grupos en situación de vulnerabilidad',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'name' => 'A6.7.- Educación para pueblos indígenas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 42,
                'name' => 'A6.8.- Educación, capacitación y/o sensibilización en Derechos Humanos a personas servidoras públicas',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 43,
                'name' => 'A6.9.- Falta un tema de Ciencie y Tecnología',
                'cat_topic_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 44,
                'name' => 'A7.1.- Medidas para disminuir el rezago educativo',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 45,
                'name' => 'A7.2.- Ejecuciones extrajudiciales cometidas por agentes del Estado',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 46,
                'name' => 'A7.3.-Guerra sucia',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 47,
                'name' => 'A7.4.- Investigación de ejecuciones extrajudiciales',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 48,
                'name' => 'A7.5.- Jurisdicción civil',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 49,
                'name' => 'A7.6.- Ratificación de instrumentos internacionales',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 50,
                'name' => 'A7.7.- Transparencia y rendición de cuentas',
                'cat_topic_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 51,
                'name' => 'A8.1.- Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 52,
                'name' => 'A8.2.- Fortalecimiento del Marco Regulatorio',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 53,
                'name' => 'A8.3.- Impacto ambiental',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 54,
                'name' => 'A8.4.- Plan de Acción Nacional sobre Empresas y Derechos Humanos',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 55,
                'name' => 'A8.5.- Respeto a los derechos humanos en actividades empresariales',
                'cat_topic_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 56,
                'name' => 'A9.1.- Capacitación y/o sensibilización a miembros de las fuerzas armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 57,
                'name' => 'A9.2.- Desapariciones forzadas cometidas por miembros de las Fuerzas Armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 58,
                'name' => 'A9.3.- Detenciones arbitrarias cometidas por miembros de las Fuerzas Armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 59,
                'name' => 'A9.4.- Ejecuciones extrajudiciales cometidas por miembros de las Fuerzas Armadas',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 60,
                'name' => 'A9.5.- Garantías de no repetición',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 61,
                'name' => 'A9.6.- Jurisdicción militar en casos de violaciones a los derechos humanos',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 62,
                'name' => 'A9.7.- Participación de las Fuerzas Armadas en tareas de seguridad pública',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 63,
                'name' => 'A9.8.- Regulación del uso legítimo de la fuerza',
                'cat_topic_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 64,
                'name' => 'A10.1.- Acceso a la justicia',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 65,
                'name' => 'A10.2.- Acceso a la verdad',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 66,
                'name' => 'A10.3.- Amnistía',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 67,
                'name' => 'A10.4.- Fortalecimiento institucional',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 68,
                'name' => 'A10.5.- Reparaciónintegral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 69,
                'name' => 'A11.1.- Acceso a la información',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 70,
                'name' => 'A11.2.- Armonización legislativa',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 71,
                'name' => 'A11.3.- Diversidad y pluralismo en los medios de comunicación',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 72,
                'name' => 'A11.4.- Investigación de delitos cometidos en contra de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 73,
                'name' => 'A11.5.- Participación de la sociedad civil',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 74,
                'name' => 'A11.6.- Prevención de delitos cometidos contra personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 75,
                'name' => 'A11.7.- Protección de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 76,
                'name' => 'A11.8.- Protesta social',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 77,
                'name' => 'A11.9.- Reparaciónintegral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 78,
                'name' => 'A12.1.- Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 79,
                'name' => 'A12.2.- Desechos peligrosos',
                'cat_topic_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 80,
                'name' => 'A12.3.- Medio ambiente y cambio climático',
                'cat_topic_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 81,
                'name' => 'A13.1.- Acceso a la justicia',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 82,
                'name' => 'A13.2.- Asesinatos cometidos contra mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 83,
                'name' => 'A13.3.- Ciudad Juárez',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 84,
                'name' => 'A13.4.- Feminicidio',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 85,
                'name' => 'A13.5.- Identificación de autores de delitos cometidos contra mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 86,
                'name' => 'A13.6.- Igualdad entre mujeres y hombres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 87,
                'name' => 'A13.7.- Implementación y promoción de programas en favor de las mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 88,
                'name' => 'A13.8.- Interrupción legal del embarazo',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 89,
                'name' => 'A13.9.- Investigación de delitos cometidos contra las mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 90,
                'name' => 'A13.10.- Mujeres afromexicanas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 91,
                'name' => 'A13.11.- Mujeres en centros de detención',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 92,
                'name' => 'A13.12.- Mujeres indígenas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 93,
                'name' => 'A13.13.- Mujeres trabajadoras',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 94,
                'name' => 'A13.14.- Mujeres trabajadoras migrantes',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 95,
                'name' => 'A13.15.- Perspectiva de género',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 96,
                'name' => 'A13.16.- Paridad de género',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 97,
                'name' => 'A13.17.- Ratificación de instrumentos internacionales',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 98,
                'name' => 'A13.18.- Salud sexual y reproductiva',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 99,
                'name' => 'A13.19.- Trabajo doméstico',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 100,
                'name' => 'A13.20.- Tráfico ilícito de mujeres y niñas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 101,
                'name' => 'A13.21.- Trata de mujeres y niñas',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 102,
                'name' => 'A13.22.- Violencia contra las mujeres',
                'cat_topic_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 103,
                'name' => 'A14.1.- Acceso a la educación para niñas, niños y adolescentes indígenas',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 104,
                'name' => 'A14.2.- Disfrute del máximo nivel de salud',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 105,
                'name' => 'A14.3.- Interés superior de la niñez',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 106,
                'name' => 'A14.4.- Matrimonio infantil',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 107,
                'name' => 'A14.5.- Armonización legislativa',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 108,
                'name' => 'A14.6.- Niñas, niños y adolescentes migrantes',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 109,
                'name' => 'A14.7.- Niñas, niños y adolescentes migrantes no acompañados',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 110,
                'name' => 'A14.8.- Niñas, niños y adolescentes solicitantes de la condición de refugiado',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 111,
                'name' => 'A14.9.- Niñas, niños y adolescentes indígenas',
                'cat_topic_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 112,
                'name' => 'A15.1.- Discriminación contra las mujeres',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 113,
                'name' => 'A15.2.- Discriminación contra Personas LGBTTTIQ+',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 114,
                'name' => 'A15.3.- Discriminación contra personas y comunidades indígenas',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 115,
                'name' => 'A15.4.- Discriminación racial',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 116,
                'name' => 'A15.5.- Acciones Afirmativas',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 117,
                'name' => 'A15.6.- Discriminación contra Personas con discapacidad',
                'cat_topic_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 118,
                'name' => 'A16.1.- Acceso a la justicia',
                'cat_topic_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 119,
                'name' => 'A16.2.- Discriminación racial',
                'cat_topic_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 120,
                'name' => 'A16.3.- Reconocimiento a las personas afromexicanas',
                'cat_topic_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 121,
                'name' => 'A17.1.- Ajustes razonables',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 122,
                'name' => 'A17.2.- Capacidad jurídica de personas con discapacidad',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 123,
                'name' => 'A17.3.- Capacitación y/o sensibilización a miembros de las fuerzas armadas',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 124,
                'name' => 'A17.4.- Consentimiento libre e informado',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 125,
                'name' => 'A17.5.- Institucionalización de personas con discapacidad',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 126,
                'name' => 'A17.6.- Medidas de accesibilidad e inclusión',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 127,
                'name' => 'A17.7.- Personas con discapacidad en zonas rurales',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 128,
                'name' => 'A17.8.- Protección de personas con dicapacidad víctimas de violencia',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 129,
                'name' => 'A17.9.- Toma de decisiones',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 130,
                'name' => 'A17.10.- Acciones afirmativas para personas con discapacidad',
                'cat_topic_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 131,
                'name' => 'A18.1.- Acceso a la información',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 132,
                'name' => 'A18.2.- Diversidad y pluralismo en los medios de comunicación',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 133,
                'name' => 'A18.3.- Investigación de delitos cometidos en contra de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 134,
                'name' => 'A18.4.- Armonización legislativa',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 135,
                'name' => 'A18.5.- Participación de la sociedad civil y las víctimas en la búsqueda de personas desaparecidas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 136,
                'name' => 'A18.6.- Prevención de delitos cometidos contra personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 137,
                'name' => 'A18.7.- Protección de personas defensoras de derechos humanos y periodistas',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 138,
                'name' => 'A18.8.- Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 139,
                'name' => 'A19.1.- Medidas de atención a personas desplazadas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 140,
                'name' => 'A19.2.- Planes de retorno para personas desplazadas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 141,
                'name' => 'A19.3.- Protección a personas desplazadas internas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 142,
                'name' => 'A19.4.- Reasentamiento de personas desplazadas internas',
                'cat_topic_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 143,
                'name' => 'A20.1.- Discriminación contra Personas LGBTTTIQ+',
                'cat_topic_id' => 20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 144,
                'name' => 'A21.1.- Acceso a la educación para personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 145,
                'name' => 'A21.2.- Acceso a la justicia',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 146,
                'name' => 'A21.3.- Acceso a la salud para personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 147,
                'name' => 'A21.4.- Alternativas a la detención migratoria / alojamiento en estaciones migratorias',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 148,
                'name' => 'A21.5.- Búsqueda de personas migrantes desaparecidas, no localizadas, secuestradas o bajo cualquier forma de privación de la ',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 149,
                'name' => 'A21.6.- Educación, capacitación y/o sensibilización en derechos humanos a personas servidoras públicas',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 150,
                'name' => 'A21.7.- Estaciones migratorias',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 151,
                'name' => 'A21.8.- Gestión migratoria',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 152,
                'name' => 'A21.9.- Mujeres trabajadoras migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 153,
                'name' => 'A21.10.- Mujeres trabajadoras migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 154,
                'name' => 'A21.11.- Niñas, niños y adolescentes migrantes no acompañados',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 155,
                'name' => 'A21.12.- Niñas, niños y adolescentes solicitantes del reconocimiento de la condición de refugiado',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 156,
                'name' => 'A21.13.- Participación de la sociedad civil',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 157,
                'name' => 'A21.14.- Personas trabajadoras migrantes mexicanas',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 158,
                'name' => 'A21.15.- Personas trabajadoras migrantes y sus familiares',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 159,
                'name' => 'A21.16.- Protección a personas migrantes, solicitantes de la condición de refugio y refugiadas',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 160,
                'name' => 'A21.17.- Tráfico ilícito de personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 161,
                'name' => 'A21.18.- Trata de personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 162,
                'name' => 'A21.19.- Unidad de investigación de delitos cometidos contra personas migrantes',
                'cat_topic_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 163,
                'name' => 'A22.1.- Acceso a la justicia',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 164,
                'name' => 'A22.2.- Acceso a la verdad',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 165,
                'name' => 'A22.3.- Comisiones de atención a víctimas',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 166,
                'name' => 'A22.4.- Fortalecimiento institucional',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 167,
                'name' => 'A22.5.- Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 168,
                'name' => 'A22.6.- Víctimas de tráfico ilícito de personas',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 169,
                'name' => 'A22.7.- Víctimas de trata de personas',
                'cat_topic_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 170,
                'name' => 'A23.1.- Conflictos agrarios',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 171,
                'name' => 'A23.2.- Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 172,
                'name' => 'A23.3.- Diversidad lingüística y cultural',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 173,
                'name' => 'A23.4.- Educación para pueblos indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 174,
                'name' => 'A23.5.- Identidad y autoadscripción indígena',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 175,
                'name' => 'A23.6.- Personas indígenas en situación de pobreza extrema',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 176,
                'name' => 'A23.7.- Respeto a usos y costumbres de personas y comunidades indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 177,
                'name' => 'A23.8.- Tierra, territorio y recursos naturales',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 178,
                'name' => 'A23.9.- Sistemas normativos indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 179,
                'name' => 'A23.10.- Traductores e intérpretes para personas indígenas',
                'cat_topic_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 180,
                'name' => 'A24.1.- Acceso a la alimentación',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 181,
                'name' => 'A24.2.- Acceso a la seguridad social',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 182,
                'name' => 'A24.3.- Acceso a servicios de salud',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 183,
                'name' => 'A24.4.- Acceso al agua potable e infraestructura de saneamiento',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 184,
                'name' => 'A24.5.- Consulta previa, libre e informada a pueblos y comunidades indígenas',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 185,
                'name' => 'A24.6.- Desigualdad',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 186,
                'name' => 'A24.7.- Política agraria',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 187,
                'name' => 'A24.8.- Seguridad social',
                'cat_topic_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 188,
                'name' => 'A25.1.- Acceso a la seguridad social',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 189,
                'name' => 'A25.2.- Asignación de presupuesto',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 190,
                'name' => 'A25.3.- Consumo de drogas',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 191,
                'name' => 'A25.4.- Interrupción legal del embarazo',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 192,
                'name' => 'A25.5.- Personas viviendo con VIH/SIDA',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 193,
                'name' => 'A25.6.- Salud mental',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 194,
                'name' => 'A25.7.- Salud sexual y reproductiva',
                'cat_topic_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 195,
                'name' => 'A26.1.- Acceso a la justicia',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 196,
                'name' => 'A26.2.- Amnistía',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 197,
                'name' => 'A26.3.- Debido proceso judicial',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 198,
                'name' => 'A26.4.- Delincuencia organizada',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 199,
                'name' => 'A26.5.- Detención y presentación ante autoridades judiciales',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 200,
                'name' => 'A26.6.- Fortalecimiento institucional',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 201,
                'name' => 'A26.7.- Impunidad',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 202,
                'name' => 'A26.8.- Participación de las Fuerzas Armadas en tareas de seguridad pública',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 203,
                'name' => 'A26.9.- Procedimientos de investigación de delitos',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 204,
                'name' => 'A26.10.- Regulación del uso legítimo de la fuerza',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 205,
                'name' => 'A26.11.- Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 206,
                'name' => 'A26.12.- Sistema de justicia penal',
                'cat_topic_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 207,
                'name' => 'A27.1.- Aplicación de las Reglas Mínimas de las Naciones Unidas para el Tratamiento de los Reclusos (Reglas Nelson Mandela)',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 208,
                'name' => 'A27.2.- Aplicación del Protocolo de Estambul para la investigación y documentación eficaces de la tortura y otros tratos o penas crueles, inhumanos o degradantes',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 209,
                'name' => 'A27.3.- Condiciones de las personas privadas de su libertad y de los centros de detención',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 210,
                'name' => 'A27.4.- Detención y presentación ante autoridades judiciales',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 211,
                'name' => 'A27.5.- Educación, capacitación y/o sensibilización en derechos humanos a personas servidoras públicas',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 212,
                'name' => 'A27.6.- Evaluación médica forense',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 213,
                'name' => 'A27.7.- Garantías de no repetición',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 214,
                'name' => 'A27.8.- Reparación integral a personas víctimas de violaciones a derechos humanos y sus familiares',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 215,
                'name' => 'A27.9.- Investigación y sanción de presuntos autores de tortura',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 216,
                'name' => 'A27.10.- Mecanismo Nacional de Prevención de la Tortura',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 217,
                'name' => 'A27.11.- Participación de la sociedad civil',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 218,
                'name' => 'A27.12.- Personas migrantes',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 219,
                'name' => 'A27.13.- Solicitantes del reconocimiento de la condición de refugio y refugiados',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 220,
                'name' => 'A27.14.- Violencia contra las mujeres',
                'cat_topic_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 221,
                'name' => 'A28.1.- Acceso a la justicia',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 222,
                'name' => 'A28.2.- Acceso a la seguridad social',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 223,
                'name' => 'A28.3.- Igualdad laboral',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 224,
                'name' => 'A28.4.- Jornada laboral',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 225,
                'name' => 'A28.5.- Legislación laboral',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 226,
                'name' => 'A28.6.- Libertad sindical',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 227,
                'name' => 'A28.7.- Mujeres trabajadoras',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 228,
                'name' => 'A28.8.- Mujeres trabajadoras migrantes',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 229,
                'name' => 'A28.9.- Ratificación de instrumentos internacionales',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 230,
                'name' => 'A28.10.- Salario mínimo',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 231,
                'name' => 'A28.11.- Seguridad social',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 232,
                'name' => 'A28.12.- Trabajadores y trabajadoras agrícolas',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 233,
                'name' => 'A28.13.- Trabajo doméstico',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 234,
                'name' => 'A28.14.- Trabajo infantil',
                'cat_topic_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 235,
                'name' => 'A29.1.- Armonización legislativa',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 236,
                'name' => 'A29.2.- Tráfico ilícito de personas migrantes',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 237,
                'name' => 'A29.3.- Tráfico ilícito de mujeres y niñas',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 238,
                'name' => 'A29.4.- Tráfico ilícito de niñas, niños y adolescentes',
                'cat_topic_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 239,
                'name' => 'A30.1.- Armonización legislativa',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 240,
                'name' => 'A30.2.- Trata de personas migrantes',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 241,
                'name' => 'A30.3.- Trata de mujeres y niñas',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 242,
                'name' => 'A30.4.- Trata de niñas, niños y adolescentes',
                'cat_topic_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 243,
                'name' => 'A31.1.- Desalojos forzosos de vivienda',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 244,
                'name' => 'A31.2.- Fomento a la vivienda',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 245,
                'name' => 'A31.3.- Fortalecimiento del Marco Regulatorio',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 246,
                'name' => 'A31.4.- Protección de personas en situación de pobreza',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 247,
                'name' => 'A31.5.- Seguridad social',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 248,
                'name' => 'A31.6.- Vivienda social',
                'cat_topic_id' => 31,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
