<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CatSubCategorySubRightsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subCategorySubrights= [
            ['id' => 1, 'sub_rights_id' => 1, 'name' => 'Derecho a no ser sometido/a a ejecuciones sumarias, extrajudiciales o arbitrarias', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 2, 'sub_rights_id' => 1, 'name' => 'Derecho a no ser sometido/a a pena de muerte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 3, 'sub_rights_id' => 2, 'name' => 'Derecho a no ser sometido/a a tortura, tratos o penas crueles, inhumanos y/o degradantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 4, 'sub_rights_id' => 2, 'name' => 'Derecho a no ser sometido/a al uso excesivo de la fuerza', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 5, 'sub_rights_id' => 3, 'name' => 'Derecho a no ser sometido/a a desaparición forzada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 6, 'sub_rights_id' => 3, 'name' => 'Derecho a no ser sometido/a a detención arbitraria y a recibir información sobre la causa de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 7, 'sub_rights_id' => 3, 'name' => 'Derecho a la presentación ante un juez en un plazo razonable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 8, 'sub_rights_id' => 3, 'name' => 'Derecho a una reparación integral en caso de detención arbitraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 9, 'sub_rights_id' => 3, 'name' => 'Derecho al control judicial de la detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 10, 'sub_rights_id' => 4, 'name' => 'Derecho al acceso a la justicia y la protección judicial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 11, 'sub_rights_id' => 4, 'name' => 'Derecho a ser juzgado/a en audiencia pública por un juez o tribunal competente, independiente e imparcial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 12, 'sub_rights_id' => 4, 'name' => 'Derecho a la igualdad entre las partes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 13, 'sub_rights_id' => 4, 'name' => 'Derecho a una defensa adecuada y gratuita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 14, 'sub_rights_id' => 4, 'name' => 'Derecho a contar con un intérprete gratuito', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 15, 'sub_rights_id' => 4, 'name' => 'Derecho a la presunción de inocencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 16, 'sub_rights_id' => 4, 'name' => 'Derecho a ser notificado/a sin demora de los cargos que se le imputan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 17, 'sub_rights_id' => 4, 'name' => 'Derecho a no ser juzgado/a por un delito que no está en la ley', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 18, 'sub_rights_id' => 4, 'name' => 'Derecho a no declarar en su contra y a no declararse culpable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 19, 'sub_rights_id' => 4, 'name' => 'Derecho de ser juzgado/a y recibir sentencia dentro de un plazo razonable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 20, 'sub_rights_id' => 4, 'name' => 'Derecho de no ser juzgado/a dos veces por el mismo delito', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 21, 'sub_rights_id' => 4, 'name' => 'Derecho a la libertad bajo caución', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 22, 'sub_rights_id' => 4, 'name' => 'Derecho a la aplicación del principio de legalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 23, 'sub_rights_id' => 4, 'name' => 'Derecho a la no aplicación retroactiva de la ley en su perjuicio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 24, 'sub_rights_id' => 4, 'name' => 'Derecho a estar presente en el proceso judicial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 25, 'sub_rights_id' => 4, 'name' => 'Derecho a que fallos y sentencias sean sometidos a control judicial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 26, 'sub_rights_id' => 4, 'name' => 'Derecho a la reparación integral del daño derivados de errores judiciales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 27, 'sub_rights_id' => 4, 'name' => 'Derecho a la publicidad de la sentencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 28, 'sub_rights_id' => 5, 'name' => 'Derecho a votar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 29, 'sub_rights_id' => 5, 'name' => 'Derecho a participar en asuntos públicos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 30, 'sub_rights_id' => 5, 'name' => 'Derecho a acceder en condiciones de igualdad a cargos públicos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 31, 'sub_rights_id' => 11, 'name' => 'Derecho a ingresar y salir del país', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 32, 'sub_rights_id' => 13, 'name' => 'Derecho a no ser objeto de cateos o revisiones ilegales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 33, 'sub_rights_id' => 14, 'name' => 'Derecho a la protección de la familia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 34, 'sub_rights_id' => 14, 'name' => 'Derecho a la libertad de matrimonio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 35, 'sub_rights_id' => 14, 'name' => 'Derecho a fundar una familia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 36, 'sub_rights_id' => 14, 'name' => 'Derecho a la igualdad de los cónyuges', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 37, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por motivos de género o sexo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 38, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por motivos de origen étnico o nacional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 39, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por motivos de religión y/o convicción de fe personal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 40, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por motivos discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 41, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por motivos de orientación sexual, identidad de género o características sexuales o corporales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 42, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por motivos linguisticos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 43, 'sub_rights_id' => 16, 'name' => 'Derecho a la igualdad y no discriminación por condición migratoria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 44, 'sub_rights_id' => 25, 'name' => 'Derecho a la protección contra la explotación laboral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 45, 'sub_rights_id' => 26, 'name' => 'Derecho a un salario equitativo e igual por trabajo de igual valor', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 46, 'sub_rights_id' => 26, 'name' => 'Derecho a una remuneración que garantice condiciones de vida dignas para los trabajadores y sus familias', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 47, 'sub_rights_id' => 26, 'name' => 'Derecho a la seguridad y la higiene en el trabajo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 48, 'sub_rights_id' => 26, 'name' => 'Derecho al descanso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 49, 'sub_rights_id' => 27, 'name' => 'Derecho a formar sindicatos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 50, 'sub_rights_id' => 27, 'name' => 'Derecho a afiliarse al sindicato de su elección', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 51, 'sub_rights_id' => 27, 'name' => 'Derecho a la libertad sindical', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 52, 'sub_rights_id' => 27, 'name' => 'Derecho de huelga, negociación y acción colectiva', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 53, 'sub_rights_id' => 29, 'name' => 'Derecho a la educación primaria obligatoria y gratuita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 54, 'sub_rights_id' => 29, 'name' => 'Derecho a la educación secundaria obligatoria y gratuita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 55, 'sub_rights_id' => 29, 'name' => 'Derecho a la educación superior', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 56, 'sub_rights_id' => 29, 'name' => 'Derecho a la libertad de establecer escuelas privadas y enviar a sus hijos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 57, 'sub_rights_id' => 29, 'name' => 'Derecho a la educación con perspectiva de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 58, 'sub_rights_id' => 30, 'name' => 'Derecho a servicios públicos de salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 59, 'sub_rights_id' => 35, 'name' => 'Derecho a libertad para investigación científica y la actividad creativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 60, 'sub_rights_id' => 35, 'name' => 'Derecho a la propiedad intelectual', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 61, 'sub_rights_id' => 36, 'name' => 'Derecho de niñas, niños y adolescentes a la protección contra toda forma de perjuicio o abuso físico o mental, descuido o trato negligente, malos tratos o explotación', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 62, 'sub_rights_id' => 36, 'name' => 'Derecho de niñas, niños y adolescentes a un nivel de vida adecuado para su desarrollo mental, espiritual, moral y social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 63, 'sub_rights_id' => 36, 'name' => 'Derecho de niñas, niños y adolescentes al disfrute del más alto nivel posible de salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 64, 'sub_rights_id' => 36, 'name' => 'Derecho de niñas, niños y adolescentes a ser registrados en su nacimiento, al nombre y la nacionalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 65, 'sub_rights_id' => 36, 'name' => 'Derecho de niñas, niños y adolescentes a no ser objetos de explotación sexual, pornografía y/o abuso sexual infantil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 66, 'sub_rights_id' => 36, 'name' => 'Derechos del entorno familiar y cuidados alternativos de niñas, niños y adolescentes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 67, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes en procedimientos judiciales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 68, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes en conflictos armados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 69, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes a la participación en todos los asuntos que les afecten', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 70, 'sub_rights_id' => 36, 'name' => 'Derecho a la aplicación del interés superior de la niñez', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 71, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 72, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes en situación de calle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 73, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes solicitantes de la condición de refugiado y asilo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 74, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 75, 'sub_rights_id' => 36, 'name' => 'Derechos de niñas, niños y adolescentes a no ser objeto de trabajo infantil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 76, 'sub_rights_id' => 37, 'name' => 'Derecho de toda mujer a una vida libre de violencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 77, 'sub_rights_id' => 37, 'name' => 'Derechos sexuales y reproductivos de las mujeres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 78, 'sub_rights_id' => 37, 'name' => 'Derechos de las mujeres migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 79, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres a las mismas condiciones, oportunidades de empleo y remuneración', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 80, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres a no ser objeto de despido por motivo de embarazo, licencia de maternidad o estado civil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 81, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres a la igualdad de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 82, 'sub_rights_id' => 37, 'name' => 'Derechos de las mujeres indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 83, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres a que se respete su integridad física, psicológica y moral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 84, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres al acceso a la justicia con perspectiva de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 85, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres al acceso a las funciones publicas de su país y a participar en los asuntos públicos, incluyendo la toma de decisiones', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 86, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres a la protección en el trabajo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 87, 'sub_rights_id' => 37, 'name' => 'Derecho de las mujeres a la igualdad de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 88, 'sub_rights_id' => 37, 'name' => 'Derechos de las mujeres solicitantes de la condición de refugio y/o asilo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 89, 'sub_rights_id' => 37, 'name' => 'Derechos de las mujeres con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 90, 'sub_rights_id' => 37, 'name' => 'Deerechos de las mujeres adultas mayores', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 91, 'sub_rights_id' => 38, 'name' => 'Derecho de las personas migrantes a un recurso de inconformidad en caso de expulsión', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 92, 'sub_rights_id' => 38, 'name' => 'Derecho de las personas migrantes a no ser objeto de deportación arbitraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 93, 'sub_rights_id' => 38, 'name' => 'Derecho de las personas migrantes a no ser objeto de expulsión masiva', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 94, 'sub_rights_id' => 38, 'name' => 'Derecho de las personas migrantes a la protección y notificación consular ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 95, 'sub_rights_id' => 39, 'name' => 'Derecho de las personas extranjeras a solicitar asilo político', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 96, 'sub_rights_id' => 39, 'name' => 'Derecho de las personas extranjeras a la reunificación familiar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 97, 'sub_rights_id' => 39, 'name' => 'Derecho de las personas en condición de refugio a la aplicación del principio de no devolución', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 98, 'sub_rights_id' => 39, 'name' => 'Derecho de las personas extranjeras a la revisión en caso de expulsión', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 99, 'sub_rights_id' => 39, 'name' => 'Derecho de las personas extranjeras a solicitar el reconocimiento de la condición de refugio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 100, 'sub_rights_id' => 40, 'name' => 'Derecho a la autodeterminación de los pueblos indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 101, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a la consulta previa, libre e informada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 102, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a conservar y aplicar sus sistemas normativos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 103, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a conservar y aplicar sus sistemas electorales y de organización política', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 104, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a disponer sobre los recursos naturales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 105, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas al reconocimiento de propiedad ancestral y posesión de tierras', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 106, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas al acceso a la justicia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 107, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a preservar, expresar y desarrollar libremente su cultura', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 108, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a ejercer libertad de conciencia, de religión y práctica espiritual', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 109, 'sub_rights_id' => 40, 'name' => 'Derecho de de los pueblos indígenas al reconocimiento de la práctica de su medicina tradicional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 110, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas a la educación intercultural y bilingüe', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 111, 'sub_rights_id' => 40, 'name' => 'Derecho de los pueblos indígenas para determinar su propio concepto desarrollo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 112, 'sub_rights_id' => 41, 'name' => 'Derecho de las personas privadas de su libertad a no ser objeto de incomunicación y aislamiento', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 113, 'sub_rights_id' => 41, 'name' => 'Derecho de las personas privadas de su libertad al acceso a la salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 114, 'sub_rights_id' => 41, 'name' => 'Derecho de las personas privadas de su libertad a condiciones dignas y salubres de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 115, 'sub_rights_id' => 41, 'name' => 'Derecho de las personas procesadas a estar separadas de las condenadas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 116, 'sub_rights_id' => 41, 'name' => 'Derecho de las personas privadas de su libertad a no ser objeto de la aplicación arbitraria del sistema disciplinario', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 117, 'sub_rights_id' => 41, 'name' => 'Derecho de las personas privadas de su libertad a no ser objeto de discriminación post carcelaria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 118, 'sub_rights_id' => 41, 'name' => 'Derecho a la separación entre hombres y mujeres en centros de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 119, 'sub_rights_id' => 42, 'name' => 'Derecho a la accesibilidad de las personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 120, 'sub_rights_id' => 42, 'name' => 'Derecho a la habilitación y rehabilitación de personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 121, 'sub_rights_id' => 42, 'name' => 'Derecho a la educación inclusiva para personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 122, 'sub_rights_id' => 42, 'name' => 'Derecho al reconocimiento e igualdad de la capacidad jurídica de las personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 123, 'sub_rights_id' => 42, 'name' => 'Derecho de las personas con discapacidad al libre desplazamiento, a elegir su lugar de residencia y nacionalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 124, 'sub_rights_id' => 42, 'name' => 'Derecho a la máxima independencia, capacidad física, mental, social y vocacional de las personas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 125, 'sub_rights_id' => 42, 'name' => 'Derecho de las personas con discapacidad al disfrute del más alto nivel posible de salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 126, 'sub_rights_id' => 42, 'name' => 'Derecho de las personas con discapacidad a la seguridad y protección en situaciones de riesgo, emergencias humanitarias y desastres naturales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 127, 'sub_rights_id' => 42, 'name' => 'Derecho de las personas con discapacidad a trabajar en igualdad de condiciones con las demás personas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 128, 'sub_rights_id' => 42, 'name' => 'Derecho de las personas con discapacidad a la participación plena y efectiva en la vida política y pública en igualdad de condiciones', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 129, 'sub_rights_id' => 42, 'name' => 'Derecho de las personas con discapacidad a la participación plena y efectiva en la vida cultural, las actividades recreativas, el esparcimiento y el deporte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 130, 'sub_rights_id' => 42, 'name' => 'Derechos de niñas, niños y adolescentes con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 131, 'sub_rights_id' => 42, 'name' => 'Derechos de las mujeres con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 132, 'sub_rights_id' => 42, 'name' => 'Derechos de las personas indígenas con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 133, 'sub_rights_id' => 42, 'name' => 'Derechos de las personas migrantes, solicitantes de la condición de refugiado y asilo con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 134, 'sub_rights_id' => 42, 'name' => 'Derechos de las personas adultas mayores con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 135, 'sub_rights_id' => 43, 'name' => 'Derecho a la protección de las personas adultas mayores', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 136, 'sub_rights_id' => 44, 'name' => 'Derecho a la memoria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 137, 'sub_rights_id' => 44, 'name' => 'Derecho a la verdad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => 138, 'sub_rights_id' => 44, 'name' => 'Derecho a la reparación integral del daño', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];

        DB::table('cat_subcategory_subrights')->insert($subCategorySubrights);
    }
}
