<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CatSubCategorySubRightsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subCategorySubrights= [
            ['id' =>1, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por condición migratoria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>2, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por motivos de género o sexo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>3, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por motivos de orientación sexual', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>4, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por motivos de origen étnico o nacional', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>5, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por motivos de religión y/o convicción de fe personal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>6, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por motivos discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>7, 'sub_rights_id' =>	2, 'name' => 'Derecho a la igualdad y no discriminación por motivos lingüísticos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>8, 'sub_rights_id' =>	3, 'name' => 'Derecho a no ser sometido/a a tortura, tratos o penas crueles, inhumanos y/o degradantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>9, 'sub_rights_id' =>	3, 'name' => 'Derecho a no ser sometido/a al uso excesivo de la fuerza', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>10, 'sub_rights_id' =>	5, 'name' => 'Derecho a ingresar y salir del país', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>11, 'sub_rights_id' =>	8, 'name' => 'Derecho a la presentación ante un juez en un plazo razonable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>12, 'sub_rights_id' =>	8, 'name' => 'Derecho a no ser sometido/a a desaparición forzada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>13, 'sub_rights_id' =>	8, 'name' => 'Derecho a no ser sometido/a a detención arbitraria y a recibir información sobre la causa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>14, 'sub_rights_id' =>	8, 'name' => 'Derecho a una reparación integral en caso de detención arbitraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>15, 'sub_rights_id' =>	8, 'name' => 'Derecho al control judicial de la detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>16, 'sub_rights_id' =>	14, 'name' => 'Derecho a no ser sometido/a a ejecuciones sumarias, extrajudiciales o arbitrarias', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>17, 'sub_rights_id' =>	14, 'name' => 'Derecho a no ser sometido/a a pena de muerte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>18, 'sub_rights_id' =>	22, 'name' => 'Derecho a contar con un intérprete gratuito', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>19, 'sub_rights_id' =>	22, 'name' => 'Derecho a estar presente en el proceso judicial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>20, 'sub_rights_id' =>	22, 'name' => 'Derecho a la aplicación del principio de legalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>21, 'sub_rights_id' =>	22, 'name' => 'Derecho a la igualdad entre las partes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>22, 'sub_rights_id' =>	22, 'name' => 'Derecho a la libertad bajo caución', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>23, 'sub_rights_id' =>	22, 'name' => 'Derecho a la no aplicación retroactiva de la ley en su perjuicio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>24, 'sub_rights_id' =>	22, 'name' => 'Derecho a la presunción de inocencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>25, 'sub_rights_id' =>	22, 'name' => 'Derecho a la publicidad de la sentencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>26, 'sub_rights_id' =>	22, 'name' => 'Derecho a la reparación integral del daño derivado de errores judiciales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>27, 'sub_rights_id' =>	22, 'name' => 'Derecho a no declarar en su contra y a no declararse culpable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>28, 'sub_rights_id' =>	22, 'name' => 'Derecho a no ser juzgado/a por un delito que no está en la ley', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>29, 'sub_rights_id' =>	22, 'name' => 'Derecho a que fallos y sentencias sean sometidos a control judicial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>30, 'sub_rights_id' =>	22, 'name' => 'Derecho a ser juzgado/a en audiencia pública por un juez o tribunal competente, independiente', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>31, 'sub_rights_id' =>	22, 'name' => 'Derecho a ser notificado/a sin demora de los cargos que se le imputan', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>32, 'sub_rights_id' =>	22, 'name' => 'Derecho a una defensa adecuada y gratuita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>33, 'sub_rights_id' =>	22, 'name' => 'Derecho al acceso a la justicia y la protección judicial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>34, 'sub_rights_id' =>	22, 'name' => 'Derecho de no ser juzgado/a dos veces por el mismo delito', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>35, 'sub_rights_id' =>	22, 'name' => 'Derecho de ser juzgado/a y recibir sentencia dentro de un plazo razonable', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>36, 'sub_rights_id' =>	23, 'name' => 'Derecho a fundar una familia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>37, 'sub_rights_id' =>	23, 'name' => 'Derecho a la igualdad de los cónyuges', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>38, 'sub_rights_id' =>	24, 'name' => 'Derecho a acceder en condiciones de igualdad a cargos públicos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>39, 'sub_rights_id' =>	24, 'name' => 'Derecho a participar en asuntos públicos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>40, 'sub_rights_id' =>	24, 'name' => 'Derecho a votar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>41, 'sub_rights_id' =>	26, 'name' => 'Derecho a la seguridad y la higiene en el trabajo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>42, 'sub_rights_id' =>	26, 'name' => 'Derecho a un salario equitativo e igual por trabajo de igual valor', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>43, 'sub_rights_id' =>	26, 'name' => 'Derecho a una remuneración que garantice condiciones de vida dignas para los trabajadores', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>44, 'sub_rights_id' =>	26, 'name' => 'Derecho a una remuneración que garantice condiciones de vida dignas para los trabajadores y sus familias', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>45, 'sub_rights_id' =>	26, 'name' => 'Derecho al descanso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>46, 'sub_rights_id' =>	28, 'name' => 'Derecho a la educación con perspectiva de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>47, 'sub_rights_id' =>	28, 'name' => 'Derecho a la educación primaria obligatoria y gratuita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>48, 'sub_rights_id' =>	28, 'name' => 'Derecho a la educación secundaria obligatoria y gratuita', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>49, 'sub_rights_id' =>	28, 'name' => 'Derecho a la educación superior', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>50, 'sub_rights_id' =>	28, 'name' => 'Derecho a la libertad de establecer escuelas privadas y enviar a sus hijos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>51, 'sub_rights_id' =>	29, 'name' => 'Derecho a servicios públicos de salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>52, 'sub_rights_id' =>	32, 'name' => 'Derecho a la propiedad intelectual', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>53, 'sub_rights_id' =>	32, 'name' => 'Derecho a libertad para investigación científica y la actividad creativa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>54, 'sub_rights_id' =>	36, 'name' => 'Derecho a la protección contra la explotación laboral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>55, 'sub_rights_id' =>	37, 'name' => 'Derecho a afiliarse al sindicato de su elección', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>56, 'sub_rights_id' =>	37, 'name' => 'Derecho a formar sindicatos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>57, 'sub_rights_id' =>	37, 'name' => 'Derecho a la libertad sindical', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>58, 'sub_rights_id' =>	37, 'name' => 'Derecho de huelga, negociación y acción colectiva', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>59, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres a la igualdad de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>60, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres a la protección en el trabajo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>61, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres a las mismas condiciones, oportunidades de empleo y remuneración', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>62, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres a no ser objeto de despido por motivo de embarazo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>63, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres a que se respete su integridad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>64, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres al acceso a la justicia con perspectiva de género', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>65, 'sub_rights_id' =>	38, 'name' => 'Derecho de las mujeres al acceso a las funciones y asuntos públicos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>66, 'sub_rights_id' =>	38, 'name' => 'Derecho de toda mujer a una vida libre de violencia', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>67, 'sub_rights_id' =>	38, 'name' => 'Derechos de las mujeres adultas mayores', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>68, 'sub_rights_id' =>	38, 'name' => 'Derechos de las mujeres con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>69, 'sub_rights_id' =>	38, 'name' => 'Derechos de las mujeres indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>70, 'sub_rights_id' =>	38, 'name' => 'Derechos de las mujeres migrantes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>71, 'sub_rights_id' =>	38, 'name' => 'Derechos de las mujeres solicitantes de la condición de refugio y/o asilo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>72, 'sub_rights_id' =>	38, 'name' => 'Derechos sexuales y reproductivos de las mujeres', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>73, 'sub_rights_id' =>	39, 'name' => 'Derechos de las personas adultas mayores indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>74, 'sub_rights_id' =>	39, 'name' => 'Derechos de las mujeres adultas mayores', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>75, 'sub_rights_id' =>	41, 'name' => 'Derecho de las personas con discapacidad a la máxima independencia,capacidad física,mental y social', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>76, 'sub_rights_id' =>	41, 'name' => 'Derecho de las personas con discapacidad a la participación en la cultura, esparcimiento y deporte', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>77, 'sub_rights_id' =>	41, 'name' => 'Derecho de las personas con discapacidad a la participación en la vida política y pública', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>78, 'sub_rights_id' =>	41, 'name' => 'Derecho de las personas con discapacidad a la seguridad y protección en situaciones de riesgo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>79, 'sub_rights_id' =>	41, 'name' => 'Derecho de las personas con discapacidad a trabajar en igualdad de condiciones con demás personas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>80, 'sub_rights_id' =>	41, 'name' => 'Derecho de las personas con discapacidad al libre desplazamiento, lugar de residencia y nacionalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>81, 'sub_rights_id' =>	41, 'name' => 'Derechos de las personas migrantes,solicitantes de la condición de refugiado,asilo con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>82, 'sub_rights_id' =>	44, 'name' => 'Derecho de las personas en condición de refugio al principio de no devolución', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>83, 'sub_rights_id' =>	44, 'name' => 'Derecho de las personas extranjeras a la reunificación familiar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>84, 'sub_rights_id' =>	44, 'name' => 'Derecho de las personas extranjeras a la revisión en caso de expulsión', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>85, 'sub_rights_id' =>	44, 'name' => 'Derecho de las personas extranjeras a solicitar asilo político', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>86, 'sub_rights_id' =>	44, 'name' => 'Derecho de las personas extranjeras a solicitar el reconocimiento de refugio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>87, 'sub_rights_id' =>	46, 'name' => 'Derecho de las personas migrantes a la protección y notificación consular', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>88, 'sub_rights_id' =>	46, 'name' => 'Derecho de las personas migrantes a no ser objeto de deportación arbitraria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>89, 'sub_rights_id' =>	46, 'name' => 'Derecho de las personas migrantes a no ser objeto de expulsión masiva', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>90, 'sub_rights_id' =>	46, 'name' => 'Derecho de las personas migrantes a un recurso de inconformidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>91, 'sub_rights_id' =>	48, 'name' => 'Derecho a no ser objeto de discriminación post carcelaria', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>92, 'sub_rights_id' =>	48, 'name' => 'Derecho a no ser objeto de la aplicación arbitraria del sistema disciplinario', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>93, 'sub_rights_id' =>	48, 'name' => 'Derecho a condiciones dignas y salubres de detención', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>94, 'sub_rights_id' =>	48, 'name' => 'Derecho de las personas privadas de libertad a no ser objeto de aislamiento', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>95, 'sub_rights_id' =>	50, 'name' => 'Derecho a la autodeterminación de los pueblos indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>96, 'sub_rights_id' =>	50, 'name' => 'Derecho de los pueblos indígenas a conservar y aplicar sus sistemas electorales y de organización', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>97, 'sub_rights_id' =>	50, 'name' => 'Derecho de los pueblos indígenas a la consulta previa, libre e informada', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>98, 'sub_rights_id' =>	51, 'name' => 'Derecho a la aplicación del interés superior de la niñez', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>99, 'sub_rights_id' =>	51, 'name' => 'Derecho de niñas, niños y adolescentes a la protección contra toda forma de malos tratos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>100, 'sub_rights_id' =>	51, 'name' => 'Derecho de niñas, niños y adolescentes a no ser objetos de explotación sexual, pornografía y/o abuso', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>101, 'sub_rights_id' =>	51, 'name' => 'Derecho de niñas, niños y adolescentes a ser registrados en su nacimiento, al nombre y la nacionalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>102, 'sub_rights_id' =>	51, 'name' => 'Derecho de niñas, niños y adolescentes a un nivel de vida adecuado para su pleno desarrollo integral', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>103, 'sub_rights_id' =>	51, 'name' => 'Derecho de niñas, niños y adolescentes al disfrute del más alto nivel posible de salud', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>104, 'sub_rights_id' =>	51, 'name' => 'Derecho de niñas,niños y adolescentes a ser registrados en su nacimiento,al nombre y la nacionalidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>105, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes a la participación en todos los asuntos que les afecten', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>106, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes a no ser objeto de trabajo infantil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>107, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes con discapacidad', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>108, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes en conflictos armados', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>109, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes en procedimientos judiciales', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>110, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes en situación de calle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>111, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes indígenas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>112, 'sub_rights_id' =>	51, 'name' => 'Derechos de niñas, niños y adolescentes solicitantes de la condición de refugiado y asilo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' =>113, 'sub_rights_id' =>	51, 'name' => 'Derechos del entorno familiar y cuidados alternativos de niñas, niños y adolescentes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

        ];

        DB::table('cat_subcategory_subrights')->insert($subCategorySubrights);
    }
}
